// Textos de interfaz (docs/06-textos.md). Español rioplatense, vos, frases cortas.
// Para ajustar un texto, se cambia acá; los componentes no tienen textos propios.
// Los textos que dependen del comercio (nombre, dirección, privacidad) salen de la configuración.

const plural = (n: number, uno: string, varios: string) => (n === 1 ? uno : varios);

export const textos = {
  general: {
    cargando: 'Cargando…',
    reintentar: 'Intentar de nuevo',
    cerrar: 'Cerrar',
    volver: 'Volver',
    errores: {
      sinConexion: 'No hay conexión. Revisá tu internet y probá de nuevo.',
      servidor: 'Algo falló de nuestro lado. Probá de nuevo en unos segundos.',
      sesion: 'Tu sesión se cerró. Volvé a entrar.',
      noEncontrado: 'No encontramos lo que buscabas.',
    },
  },

  tienda: {
    abrirMenu: 'Abrir menú',
    cerrarMenu: 'Cerrar menú',
    volverCatalogo: 'Volver al catálogo',
    carrito: (n: number) => `Carrito, ${n} ${plural(n, 'producto', 'productos')}`,
    buscar: 'Buscar productos',
    todo: 'Todo',
    todoDe: (categoria: string) => `Todo ${categoria}`,
    resultados: (n: number, termino: string) => `${n} ${plural(n, 'producto', 'productos')} para “${termino}”`,
    sinResultados: (termino: string) => `No encontramos “${termino}”`,
    sinResultadosAyuda: 'Probá con otra palabra o mirá las categorías.',
    consultarWhatsapp: 'Consultar por WhatsApp',
    categoriaVacia: 'Todavía no hay productos en esta categoría.',
    verTodo: 'Ver todo',
    sinStock: 'Sin stock',
    menuConsultas: 'Consultas por WhatsApp',
    menuHorarios: 'Horarios',
    menuRedes: 'Seguinos',
    barraCarrito: (n: number) => `Ver carrito · ${n}`,
    errorCatalogo: 'No pudimos cargar los productos.',

    // Ficha
    color: (c: string) => `Color: ${c}`,
    talle: 'Talle',
    elegiTalle: 'Elegí un talle para ver el stock.',
    sinStockOpcion: 'Sin stock en esta opción',
    pocas: (n: number, talle: string) => (n === 1 ? 'Queda 1' : `Quedan ${n}`) + (talle ? ` en talle ${talle}` : ''),
    yaEnCarrito: (n: number) => `Ya tenés ${n} en el carrito.`,
    restar: 'Restar uno',
    sumar: 'Sumar uno',
    agregar: 'Agregar al carrito',
    agregado: (producto: string, variante: string) => `Agregaste ${producto}${variante ? ` (${variante})` : ''} al carrito.`,
    descripcion: 'Descripción',
    consultaTalle: '¿Dudas con el talle? Consultanos por WhatsApp',
    consultaMensaje: (producto: string) => `Hola, tengo una consulta sobre ${producto}.`,
    productoNoEncontrado: 'Este producto ya no está disponible.',
    fotoDe: (producto: string, n: number, total: number) => `${producto}, foto ${n} de ${total}`,
    verFoto: (n: number) => `Ver foto ${n}`,

    // Carrito
    tuCarrito: 'Tu carrito',
    carritoVacio: 'Tu carrito está vacío.',
    verProductos: 'Ver productos',
    agotado: 'Se agotó mientras elegías',
    agotadoAyuda: 'Elegí otra opción o quitalo para seguir.',
    parcial: (n: number) => `Quedan ${n} de esta opción`,
    parcialAyuda: 'Bajá la cantidad para seguir.',
    noDisponible: 'Este producto ya no está disponible',
    noDisponibleAyuda: 'Quitalo para seguir.',
    verOtrasOpciones: 'Ver otras opciones',
    quitar: 'Quitar',
    subtotal: 'Subtotal',
    avisoEnvio: 'El envío se cotiza por WhatsApp. Si elegís retiro, no tiene costo.',
    continuar: 'Continuar',
    resolverAntes: 'Resolvé los productos marcados para continuar.',
    precioCambio: 'El precio se actualizó.',

    // Datos del comprador
    tusDatos: 'Tus datos',
    revisa: (n: number) => `Revisá ${n} ${plural(n, 'dato', 'datos')}`,
    nombre: 'Nombre',
    whatsapp: 'Tu WhatsApp',
    whatsappAyuda: 'Para que la tienda pueda responderte. Con o sin 0 y 15.',
    whatsappQuedo: (n: string) => `Te van a escribir al ${n}`,
    comoRecibis: '¿Cómo lo recibís?',
    envio: 'Envío a domicilio',
    envioAyuda: 'El costo te lo pasan por WhatsApp',
    retiro: 'Retiro en el local',
    retiroAyuda: (direccion: string) => `${direccion} · sin costo`,
    direccion: 'Dirección de entrega',
    direccionEjemplo: 'Calle, número, piso y depto.',
    localidad: 'Localidad',
    comoPagas: '¿Cómo preferís pagar?',
    transferencia: 'Transferencia',
    efectivo: 'Efectivo',
    nota: 'Nota',
    notaEjemplo: 'Ej.: horario para recibir',
    opcional: '(opcional)',
    resumen: (n: number, total: string) => `${n} ${plural(n, 'producto', 'productos')} · ${total} + envío a cotizar`,
    enviarPedido: 'Enviar pedido por WhatsApp',
    errNombre: 'Escribí tu nombre.',
    errWhatsapp: 'Escribí tu WhatsApp con código de área, por ejemplo 11 5555 0000.',
    errDireccion: 'Escribí la dirección de entrega.',
    errLocalidad: 'Escribí la localidad.',
    carritoCambio: 'Algunos productos cambiaron mientras completabas tus datos. Revisalos en el carrito.',

    // Enviando
    enviando: 'Enviando pedido…',
    reservaAlEnviar: (h: number) => `Al enviarlo, te reservamos los productos por ${h} h.`,
    noCierres: 'Estamos reservando tus productos. No cierres esta pantalla.',
    errorEnvioTitulo: 'No pudimos registrar tu pedido',
    errorEnvioAyuda: 'Tus productos y tus datos siguen guardados.',

    // Pedido registrado
    tuNumero: 'Tu número de pedido',
    reservamos: (h: number, fecha: string) => `Te reservamos los productos por ${h} h (hasta ${fecha}).`,
    ultimoPaso: 'Último paso: mandá el mensaje',
    ultimoPasoAyuda: 'Tocá el botón: se abre WhatsApp con tu pedido escrito y solo tenés que enviarlo.',
    abrirWhatsapp: 'Abrir WhatsApp',
    siNoSeAbrio: 'Si no se abrió WhatsApp, tocá acá',
    copiar: 'Copiar el mensaje',
    copiado: 'Mensaje copiado.',
    copiarManual: 'Seleccioná el mensaje y copialo.',
    asiLlega: 'Así llega el mensaje',
    queSigue: 'Qué sigue',
    queSigueTexto: 'La tienda te responde por WhatsApp con el costo de envío y los datos para pagar.',
    volverTienda: 'Volver a la tienda',
    sinPedido: 'No encontramos un pedido reciente en este navegador.',
  },

  /** Mensaje de WhatsApp del comprador a la tienda (06-textos.md). */
  mensajePedido: {
    saludo: 'Hola, quiero hacer este pedido:',
    pedido: (n: number) => `Pedido #${n}`,
    subtotal: (total: string) => `Subtotal: ${total} (envío a cotizar)`,
    nombre: (n: string) => `Nombre: ${n}`,
    envio: (direccion: string, localidad: string) => `Entrega: envío a ${direccion}, ${localidad}`,
    retiro: 'Entrega: retiro en el local',
    pago: (p: string) => `Pago: ${p}`,
    nota: (n: string) => `Nota: ${n}`,
  },

  admin: {
    // Ingreso
    ingresoTitulo: 'Administrá tu tienda',
    ingresoSubtitulo: 'Pedidos, productos y stock, desde el celular.',
    entrar: 'Entrar con Google',
    entrarSimulado: 'Entrar con Google (simulado)',
    ingresoAyuda: 'Entrá con la cuenta de Google de tu negocio. Con otra cuenta, Google no te va a dejar pasar.',
    ingresoSimuladoAyuda:
      'Modo de prueba: el ingreso es simulado. En la versión real, solo entra la cuenta de Google del negocio.',
    tipInicio: 'Tip: agregá esta página a la pantalla de inicio del celular para tenerla a mano.',
    ayudaWhatsapp: '¿Necesitás ayuda? Escribinos por WhatsApp',
    salir: 'Salir',
    verMiTienda: 'Ver mi tienda',
    navegacion: 'Secciones del admin',

    pedidos: 'Pedidos',
    productos: 'Productos',

    // Pedidos
    filtros: { pendiente: 'Pendientes', confirmada: 'Confirmadas', cancelada: 'Canceladas', vencida: 'Vencidas', todas: 'Todas' },
    estados: { pendiente: 'Pendiente', confirmada: 'Confirmada', cancelada: 'Cancelada', vencida: 'Vencida' },
    buscarPedido: 'Buscar por número o nombre',
    alDia: 'Estás al día',
    alDiaTexto: 'No hay pedidos pendientes. Cuando alguien compre en tu tienda, el pedido aparece acá y te llega el WhatsApp.',
    copiarLink: 'Copiar link de mi tienda',
    linkCopiado: 'Link copiado.',
    sinPedidosEstado: 'No hay pedidos en este estado.',
    sinPedidosBusqueda: 'No hay pedidos con ese número o nombre.',
    reserva: (t: string) => `Reserva · ${t}`,
    reservaDetalle: (t: string) => `Stock reservado · ${t}`,
    reservaDetalleAyuda: 'Si no confirmás antes, vuelve a la tienda.',
    vencidaDetalle: 'La reserva venció y el stock volvió a la tienda. Podés confirmarlo igual si el comprador te escribió.',
    confirmar: 'Confirmar',
    confirmarVenta: 'Confirmar venta',
    cancelar: 'Cancelar',
    cancelarPedido: 'Cancelar pedido',
    cancelarConfirmada: 'Cancelar (devuelve el stock)',
    confirmando: 'Confirmando…',
    cancelando: 'Cancelando…',
    puedeTardar: 'Puede tardar unos segundos. No hace falta tocar de nuevo.',
    verDetalle: 'Ver detalle',
    avisoConfirmado: (n: number) => `Venta #${n} confirmada. Se descontó del stock.`,
    avisoCancelado: (n: number) => `Pedido #${n} cancelado. El stock volvió a la tienda.`,
    deshacer: 'Deshacer',
    deshecho: 'Listo, se deshizo el cambio.',
    pedidoN: (n: number) => `Pedido #${n}`,
    volverPedidos: 'Volver a pedidos',
    productosDelPedido: 'Productos',
    totalSinEnvio: 'Total (sin envío)',
    codigoCorto: (c: string) => `Cód. ${c}`,
    comprador: 'Comprador',
    whatsappDe: (n: string) => `WhatsApp · ${n}`,
    entregaEnvio: (d: string, l: string) => `Envío · ${d}, ${l}`,
    entregaRetiro: 'Retiro en el local',
    pagaCon: (p: string) => `Paga con ${p}`,
    notaComprador: (n: string) => `Nota: “${n}”`,
    abrirChat: 'Abrir chat de WhatsApp',
    mensajeComprador: (nombre: string, n: number) => `Hola ${nombre}, te escribo por tu pedido #${n}.`,
    tablaNumero: 'N.º',
    tablaComprador: 'Comprador',
    tablaProductos: 'Productos',
    tablaTotal: 'Total',
    tablaEstado: 'Reserva / estado',
    tablaAccion: 'Acción',
    elegiPedido: 'Elegí un pedido para ver el detalle.',

    // Vencido sin stock
    vencidoSinStock: 'No queda stock libre de este talle',
    vencidoSinStockTexto: 'Mientras el pedido estaba vencido, otra persona lo pidió o lo descontaste por una venta en el local.',
    avisarle: 'Avisarle por WhatsApp',
    mensajeAgotado: (nombre: string, productos: string, n: number) =>
      `Hola ${nombre}, lamentablemente se agotó ${productos} de tu pedido #${n}.`,
    confirmarIgual: 'Confirmar igual, tengo la prenda',
    confirmarIgualAyuda: 'Si confirmás igual, el stock de ese talle queda en 0 hasta que lo corrijas.',
    volverSinCambios: 'Volver sin cambios',

    // Productos
    agregar: '+ Agregar',
    buscarProducto: 'Buscar producto o código',
    avisoStock: '¿Vendiste en el local o por Instagram? Abrí el producto y descontalo acá.',
    avisoStockAyuda: 'Este es el stock total del negocio.',
    stockN: (n: number) => `Stock ${n}`,
    oculto: 'Oculto',
    sinProductos: 'No hay productos con ese nombre o código.',
    todasCategorias: 'Todas las categorías',
    filtrarCategoria: 'Filtrar por categoría',
    tablaProducto: 'Producto',
    tablaCategoria: 'Categoría',
    tablaPrecio: 'Precio',
    tablaStock: 'Stock',
    tablaVisible: 'En la tienda',
    visibleSi: 'Visible',
    unidades: 'Unidades',
    colorTab: (c: string, n: number) => `${c} · ${n}`,
    guardando: 'Guardando…',
    guardado: 'Cambios guardados',
    noSeGuardo: 'No se pudo guardar',
    reintentar: 'Reintentar',
    reservadas: (n: number, pedidos: string) => `${n} ${plural(n, 'reservada', 'reservadas')} en ${pedidos}`,
    reservaAfectada: (n: number, pedidos: string) =>
      `Hay ${n} ${plural(n, 'reservada', 'reservadas')} en ${pedidos}. A ese pedido le falta la prenda. Avisale al comprador o cancelá el pedido.`,
    verPedido: (n: number) => `Ver pedido #${n}`,
    editarProducto: 'Editar producto',
    abrirAjuste: (p: string) => `Ajustar stock de ${p}`,

    // Formulario
    nuevoProducto: 'Nuevo producto',
    editar: 'Editar producto',
    volverProductos: 'Volver a productos',
    reglaFormulario: 'Cada campo es lo que el comprador ve en la ficha de la tienda (salvo el código, que es interno).',
    faltan: (n: number) => `Faltan ${n} ${plural(n, 'dato', 'datos')} para guardar`,
    noSePierde: 'Lo que ya completaste no se pierde.',
    fotos: 'Fotos',
    agregarFotos: 'Agregar fotos',
    agregarFotosAyuda: 'Elegí, sacá o arrastrá',
    fotosAyuda: 'Las achicamos antes de guardarlas. La primera es la principal.',
    principal: 'Principal',
    hacerPrincipal: 'Hacer principal',
    quitarFoto: (n: number) => `Quitar foto ${n}`,
    hacerPrincipalN: (n: number) => `Usar la foto ${n} como principal`,
    fotoN: (n: number) => `Foto ${n}`,
    preparandoFotos: 'Preparando fotos…',
    fotoNoSirve: 'No pudimos leer una de las fotos. Probá con otra (JPG o PNG).',
    asiSeVe: 'Así se ve en la tienda',
    nombreProducto: 'Nombre',
    nombreEjemplo: 'Nombre del producto',
    categoria: 'Categoría',
    elegiCategoria: 'Elegí una categoría',
    categoriaAyuda: '¿Falta una categoría? Pedila por WhatsApp y la sumamos.',
    precio: 'Precio',
    precioEjemplo: 'Ej.: 15000',
    precioAyuda: 'Podés escribir 15000 o 15.000.',
    descripcion: 'Descripción',
    colores: 'Colores',
    coloresEjemplo: 'Ej.: Negro',
    talles: 'Talles',
    tallesEjemplo: 'Ej.: M o 38',
    sumarItem: 'Sumar',
    quitarItem: (v: string) => `Quitar ${v}`,
    stock: 'Stock',
    stockCombinaciones: 'Stock de cada combinación',
    stockDe: (v: string) => `Stock ${v}`,
    masOpciones: 'Más opciones',
    codigo: 'Código del producto',
    codigoAyuda: 'Propio o de tu proveedor. No se muestra en la tienda.',
    codigoRepetido: (c: string, p: string) => `“${c}” ya lo usa ${p}. Podés guardarlo igual o cambiarlo.`,
    mostrar: 'Mostrar en la tienda',
    mostrarAyuda: 'Si lo apagás, se oculta pero no se borra.',
    guardar: 'Guardar producto',
    cancelarForm: 'Cancelar',
    guardandoFotos: (n: number) => (n > 0 ? `Guardando… subiendo ${n} ${plural(n, 'foto', 'fotos')}` : 'Guardando…'),
    datosMoviles: 'Con datos móviles puede tardar un poco. No cierres esta pantalla.',
    productoGuardado: 'Producto guardado. Ya aparece en la tienda.',
    productoGuardadoOculto: 'Producto guardado. Está oculto: no aparece en la tienda.',
    eliminar: 'Eliminar producto',
    eliminarPregunta: (p: string) => `¿Eliminar “${p}”?`,
    eliminarAyuda: 'No se puede deshacer. Si solo no lo vendés por un tiempo, ocultalo.',
    eliminarSi: 'Sí, eliminar',
    eliminarNo: 'No',
    eliminado: 'Producto eliminado.',
    errFotos: 'Agregá al menos una foto.',
    errNombre: 'Escribí el nombre del producto.',
    errCategoria: 'Elegí una categoría.',
    errPrecio: 'Escribí el precio, por ejemplo 15000.',
    stockDescartado: 'Vas a descartar stock',
    stockDescartadoTexto: (detalle: string) =>
      `Quitaste opciones que tenían unidades: ${detalle}. Si guardás, ese stock se descarta.`,
    guardarIgual: 'Guardar igual',
    revisar: 'Revisar',
    productoNoExiste: 'Este producto ya no existe.',
  },

  pruebas: {
    boton: 'Herramientas de prueba',
    titulo: 'Herramientas de prueba',
    ayuda: 'No forman parte del producto. Sirven para probar el flujo. Los datos se guardan solo en este navegador.',
    whatsapp: 'WhatsApp de la tienda (para recibir los pedidos de prueba)',
    whatsappAyuda: 'Poné tu número: así el mensaje del comprador te llega a vos.',
    horas: 'Duración de la reserva (horas)',
    demora: 'Demora del servidor',
    demoraRealista: 'Realista (1 a 3 s)',
    demoraNinguna: 'Sin demora',
    error: 'Próxima llamada',
    errorNinguno: 'Funciona bien',
    errorSinConexion: 'Falla: sin conexión',
    errorServidor: 'Falla: error del servidor',
    guardar: 'Guardar',
    guardado: 'Configuración guardada.',
    adelantar: (h: number, n: number) => `Simular que pasaron ${h} h (vencen ${n} ${plural(n, 'pendiente', 'pendientes')})`,
    adelantado: (h: number) => `Pasaron ${h} h. Las reservas pendientes vencieron.`,
    restaurar: 'Volver a los datos de ejemplo',
    restaurado: 'Datos de ejemplo restaurados.',
    irTienda: 'Ir a la tienda',
    irAdmin: 'Ir al admin',
  },
};

export type Textos = typeof textos;
